global using App.Utils.EntityFrameworkCore.Core.BaseRepository;
global using App.Utils.Extensions.Helpers.PersonalExceptions.Extensions;
global using AutoMapper;
global using Domain.ApiTest.Entities;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;